// Code generated by protoc-gen-go from "state.proto"
// DO NOT EDIT!

package stateproto

import proto "code.google.com/p/goprotobuf/proto"
import "encoding/json"
import "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type State struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Message          []byte `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	XBytes           []byte `protobuf:"bytes,3,req,name=x_bytes" json:"x_bytes,omitempty"`
	PublicBytes      []byte `protobuf:"bytes,4,req,name=public_bytes" json:"public_bytes,omitempty"`
	SharedKey        []byte `protobuf:"bytes,5,opt,name=shared_key" json:"shared_key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *State) Reset()         { *this = State{} }
func (this *State) String() string { return proto.CompactTextString(this) }
func (*State) ProtoMessage()       {}

func (this *State) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *State) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *State) GetXBytes() []byte {
	if this != nil {
		return this.XBytes
	}
	return nil
}

func (this *State) GetPublicBytes() []byte {
	if this != nil {
		return this.PublicBytes
	}
	return nil
}

func (this *State) GetSharedKey() []byte {
	if this != nil {
		return this.SharedKey
	}
	return nil
}

func init() {
}
